/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ahuja
 */
public class AdminFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        for(int i=0;i<19;i++){
        maintable.getColumnModel().getColumn(i).setPreferredWidth(200);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainscroll = new javax.swing.JScrollPane();
        maintable = new javax.swing.JTable();
        emptybtn = new javax.swing.JButton();
        showalldata = new javax.swing.JButton();
        delalldata = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        maintf = new javax.swing.JTextField();
        deldata = new javax.swing.JButton();
        showdata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BGLabel = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(728, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainscroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        maintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pick Up Location", "Drop Off Location", "Pick Up Time", "Drop Off Time", "Number Of Hours", "Selected Car", "Hourly Price", "First Name", "Last Name", "Contact", "E-mail", "Payment Method", "Card Number", "Cardholder Name", "Billing Address", "Billing City", "Luxor Code", "Grand Total", "Username"
            }
        ));
        maintable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        mainscroll.setViewportView(maintable);

        getContentPane().add(mainscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 680, 160));

        emptybtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        emptybtn.setForeground(new java.awt.Color(51, 0, 51));
        emptybtn.setText("Empty Table");
        emptybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptybtnActionPerformed(evt);
            }
        });
        getContentPane().add(emptybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, -1));

        showalldata.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        showalldata.setForeground(new java.awt.Color(51, 0, 51));
        showalldata.setText("Show All Data");
        showalldata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showalldataActionPerformed(evt);
            }
        });
        getContentPane().add(showalldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, -1));

        delalldata.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        delalldata.setForeground(new java.awt.Color(51, 0, 51));
        delalldata.setText("Delete All Data");
        delalldata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delalldataActionPerformed(evt);
            }
        });
        getContentPane().add(delalldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 270, -1));

        closebtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        closebtn.setForeground(new java.awt.Color(51, 0, 51));
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 450, -1));

        mainpanel.setBackground(new java.awt.Color(51, 0, 51));
        mainpanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("--------Search For A Specific Booking--------");
        mainpanel.add(jLabel2);
        jLabel2.setBounds(77, 0, 520, 40);

        maintf.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        mainpanel.add(maintf);
        maintf.setBounds(290, 40, 177, 26);

        deldata.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        deldata.setForeground(new java.awt.Color(51, 0, 51));
        deldata.setText("Delete");
        deldata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deldataActionPerformed(evt);
            }
        });
        mainpanel.add(deldata);
        deldata.setBounds(490, 70, 160, 33);

        showdata.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        showdata.setForeground(new java.awt.Color(51, 0, 51));
        showdata.setText("Show Data");
        showdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdataActionPerformed(evt);
            }
        });
        mainpanel.add(showdata);
        showdata.setBounds(280, 70, 200, 33);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Luxor Code:");
        mainpanel.add(jLabel1);
        jLabel1.setBounds(90, 30, 190, 40);

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 680, 110));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg2.jpg")); // NOI18N
        getContentPane().add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 880, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String CODE;
    private void showalldataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showalldataActionPerformed
        // TODO add your handling code here:
        emptybtn.doClick();
        DefaultTableModel model = (DefaultTableModel) maintable.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from admin;";
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getFloat(5),rs.getString(6),
                    rs.getFloat(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),
                    rs.getString(13),rs.getString(14),rs.getString(15),rs.getString(16),rs.getString(17),rs.getFloat(18),rs.getString(19)
                } );
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity: Show All Data");
        }
    }//GEN-LAST:event_showalldataActionPerformed

    private void deldataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deldataActionPerformed
        // TODO add your handling code here:
    int reply = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Delete?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
        CODE=maintf.getText();
        emptybtn.doClick();
        DefaultTableModel model = (DefaultTableModel) maintable.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from admin where luxorcode='"+CODE+"';";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
            maintf.setText("");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity: Show All Data");
        }               
        }
        else {
        }        
    }//GEN-LAST:event_deldataActionPerformed

    private void showdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdataActionPerformed
        // TODO add your handling code here:
        CODE=maintf.getText();
        emptybtn.doClick();
        DefaultTableModel model = (DefaultTableModel) maintable.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from admin where luxorcode='"+CODE+"';";
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getFloat(5),rs.getString(6),
                    rs.getFloat(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),
                    rs.getString(13),rs.getString(14),rs.getString(15),rs.getString(16),rs.getString(17),rs.getFloat(18),rs.getString(19)
                } );
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity: Show All Data");
        }        
    }//GEN-LAST:event_showdataActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void emptybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptybtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) maintable.getModel();
        int rows = model.getRowCount();
        if (rows>0){
            for (int i=0;i<rows;i++) {
                model.removeRow(0);
            }
        }
    }//GEN-LAST:event_emptybtnActionPerformed

    private void delalldataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delalldataActionPerformed
        // TODO add your handling code here:
    int reply = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Delete ALL Data?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
        emptybtn.doClick();
        DefaultTableModel model = (DefaultTableModel) maintable.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from admin;";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
            maintf.setText("");
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity: Show All Data");
        }               
        }
        else {
        }        
    }//GEN-LAST:event_delalldataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton delalldata;
    private javax.swing.JButton deldata;
    private javax.swing.JButton emptybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JScrollPane mainscroll;
    private javax.swing.JTable maintable;
    private javax.swing.JTextField maintf;
    private javax.swing.JButton showalldata;
    private javax.swing.JButton showdata;
    // End of variables declaration//GEN-END:variables
}
