/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahuja
 */
public class Frame2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        tf1.setVisible(false);
        tf2.setVisible(false);
        tf3.setVisible(false);
        tf4.setVisible(false);
        tf5.setVisible(false);
        tf6.setVisible(false);
        tf7.setVisible(false);
        tf8.setVisible(false);
        tf9.setVisible(false);
        tf10.setVisible(false);
        tf11.setVisible(false);
        tf12.setVisible(false);
        tf13.setVisible(false);
        tf14.setVisible(false);
        tf15.setVisible(false);
        tf16.setVisible(false);
        tf17.setVisible(false);
        tf18.setVisible(false);
        tf19.setVisible(false);
        tf20.setVisible(false);
        tf21.setVisible(false);
        tf22.setVisible(false);
        OKBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlabel = new javax.swing.JLabel();
        maintf = new javax.swing.JTextField();
        mainbtn = new javax.swing.JButton();
        c1b = new javax.swing.JLabel();
        tf22 = new javax.swing.JLabel();
        tf1 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        tf6 = new javax.swing.JLabel();
        tf7 = new javax.swing.JLabel();
        tf3 = new javax.swing.JLabel();
        c1a = new javax.swing.JLabel();
        tf8 = new javax.swing.JLabel();
        c3e = new javax.swing.JLabel();
        tf17 = new javax.swing.JLabel();
        c1c = new javax.swing.JLabel();
        tf5 = new javax.swing.JLabel();
        c1d = new javax.swing.JLabel();
        tf2 = new javax.swing.JLabel();
        tf4 = new javax.swing.JLabel();
        c1e = new javax.swing.JLabel();
        tf11 = new javax.swing.JLabel();
        tf16 = new javax.swing.JLabel();
        c1f = new javax.swing.JLabel();
        c2a = new javax.swing.JLabel();
        tf12 = new javax.swing.JLabel();
        c2b = new javax.swing.JLabel();
        tf9 = new javax.swing.JLabel();
        tf10 = new javax.swing.JLabel();
        c2c = new javax.swing.JLabel();
        tf13 = new javax.swing.JLabel();
        c2d = new javax.swing.JLabel();
        tf15 = new javax.swing.JLabel();
        c3a = new javax.swing.JLabel();
        tf18 = new javax.swing.JLabel();
        c3b = new javax.swing.JLabel();
        tf20 = new javax.swing.JLabel();
        c3c = new javax.swing.JLabel();
        tf19 = new javax.swing.JLabel();
        c3d = new javax.swing.JLabel();
        tf14 = new javax.swing.JLabel();
        tf21 = new javax.swing.JLabel();
        OKBtn = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(728, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainlabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        mainlabel.setForeground(new java.awt.Color(255, 255, 255));
        mainlabel.setText("Please Enter Your Luxor Code:");
        getContentPane().add(mainlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 480, 60));

        maintf.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        maintf.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(maintf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 240, -1));

        mainbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        mainbtn.setForeground(new java.awt.Color(51, 0, 51));
        mainbtn.setText("Enter");
        mainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 380, -1));

        c1b.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c1b.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 220, 30));

        tf22.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf22.setForeground(new java.awt.Color(255, 255, 255));
        tf22.setText("Madhya Pradesh, India");
        getContentPane().add(tf22, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 220, 30));

        tf1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 255, 255));
        tf1.setText("Luxor Luxury Car Rentals");
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 390, 50));

        c4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, 30));

        tf6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf6.setForeground(new java.awt.Color(255, 255, 255));
        tf6.setText("Drop Off Location:");
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 30));

        tf7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf7.setForeground(new java.awt.Color(255, 255, 255));
        tf7.setText("Drop Off Time:");
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, 30));

        tf3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf3.setForeground(new java.awt.Color(255, 255, 255));
        tf3.setText("Pick Up Location:");
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        c1a.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c1a.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, 30));

        tf8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf8.setForeground(new java.awt.Color(255, 255, 255));
        tf8.setText("Hourly Price:");
        getContentPane().add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, 30));

        c3e.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c3e.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c3e, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 220, 30));

        tf17.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf17.setForeground(new java.awt.Color(255, 255, 255));
        tf17.setText("Billing City:");
        getContentPane().add(tf17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 30));

        c1c.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c1c.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1c, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, 30));

        tf5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf5.setForeground(new java.awt.Color(255, 255, 255));
        tf5.setText("Selected Car:");
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        c1d.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c1d.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1d, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 220, 30));

        tf2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tf2.setForeground(new java.awt.Color(255, 255, 255));
        tf2.setText("General Info:");
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 30));

        tf4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf4.setForeground(new java.awt.Color(255, 255, 255));
        tf4.setText("Pick Up Time:");
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, 30));

        c1e.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c1e.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1e, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 30));

        tf11.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf11.setForeground(new java.awt.Color(255, 255, 255));
        tf11.setText("Contact:");
        getContentPane().add(tf11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 70, 30));

        tf16.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf16.setForeground(new java.awt.Color(255, 255, 255));
        tf16.setText("Card Holder Name:");
        getContentPane().add(tf16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 30));

        c1f.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c1f.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c1f, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 220, 30));

        c2a.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c2a.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, 30));

        tf12.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf12.setForeground(new java.awt.Color(255, 255, 255));
        tf12.setText("Last Name:");
        getContentPane().add(tf12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 90, 30));

        c2b.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c2b.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 220, 30));

        tf9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tf9.setForeground(new java.awt.Color(255, 255, 255));
        tf9.setText("Customer Info:");
        getContentPane().add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 30));

        tf10.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf10.setForeground(new java.awt.Color(255, 255, 255));
        tf10.setText("First Name:");
        getContentPane().add(tf10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, 30));

        c2c.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c2c.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 220, 30));

        tf13.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf13.setForeground(new java.awt.Color(255, 255, 255));
        tf13.setText("E-mail:");
        getContentPane().add(tf13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, 30));

        c2d.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c2d.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c2d, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 220, 30));

        tf15.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf15.setForeground(new java.awt.Color(255, 255, 255));
        tf15.setText("Payment Method:");
        getContentPane().add(tf15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 30));

        c3a.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c3a.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, 30));

        tf18.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf18.setForeground(new java.awt.Color(255, 255, 255));
        tf18.setText("Card Number:");
        getContentPane().add(tf18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 100, 30));

        c3b.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c3b.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 220, 30));

        tf20.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf20.setForeground(new java.awt.Color(255, 255, 255));
        tf20.setText("State & Country:");
        getContentPane().add(tf20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 130, 30));

        c3c.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c3c.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c3c, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 30));

        tf19.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tf19.setForeground(new java.awt.Color(255, 255, 255));
        tf19.setText("Billing Address:");
        getContentPane().add(tf19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, 30));

        c3d.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        c3d.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(c3d, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 220, 30));

        tf14.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tf14.setForeground(new java.awt.Color(255, 255, 255));
        tf14.setText("Payment Info:");
        getContentPane().add(tf14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 30));

        tf21.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        tf21.setForeground(new java.awt.Color(255, 255, 255));
        tf21.setText("Grand Total:");
        getContentPane().add(tf21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 30));

        OKBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        OKBtn.setForeground(new java.awt.Color(51, 0, 51));
        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });
        getContentPane().add(OKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 290, -1));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg2.jpg")); // NOI18N
        getContentPane().add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 880, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String puloc="";
    String doloc="";
    String putime="";
    String dotime="";
    String car="";
    float hourlyprice;
    String fn="";
    String ln="";
    String contact="";
    String email="";
    String paymethod="";
    String cardno="";
    String cardname="";
    String billadd="";
    String billcity="";
    float grandtotal;
    String CODE;
    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_OKBtnActionPerformed

    private void mainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbtnActionPerformed
        // TODO add your handling code here:
        CODE = maintf.getText();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from admin where luxorcode='"+CODE+"';";
            ResultSet rs = stmt.executeQuery(q);
            if (rs.next()){
                puloc=rs.getString(1);
                doloc=rs.getString(2);
                putime = rs.getString(3);
                dotime = rs.getString(4);
                car = rs.getString(6);
                hourlyprice = rs.getFloat(7);
                fn = rs.getString(8);
                ln = rs.getString(9);
                contact = rs.getString(10);
                email = rs.getString(11);
                paymethod = rs.getString(12);
                cardno = rs.getString(13);
                cardname = rs.getString(14);
                billadd = rs.getString(15);
                billcity = rs.getString(16);
                grandtotal = rs.getFloat(18);
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error In Connectivity");
        }
        if(cardno.equals("")){
            JOptionPane.showMessageDialog(null,"ERROR: Luxor Code Not Found\nTry Again");
        }
        else{
            mainlabel.setVisible(false);
            maintf.setVisible(false);
            mainbtn.setVisible(false);
            tf1.setVisible(true);
            tf2.setVisible(true);
            tf3.setVisible(true);
            tf4.setVisible(true);
            tf5.setVisible(true);
            tf6.setVisible(true);
            tf7.setVisible(true);
            tf8.setVisible(true);
            tf9.setVisible(true);
            tf10.setVisible(true);
            tf11.setVisible(true);
            tf12.setVisible(true);
            tf13.setVisible(true);
            tf14.setVisible(true);
            tf15.setVisible(true);
            tf16.setVisible(true);
            tf17.setVisible(true);
            tf18.setVisible(true);
            tf19.setVisible(true);
            tf20.setVisible(true);
            tf21.setVisible(true);
            tf22.setVisible(true);
            OKBtn.setVisible(true);
            c1a.setText(puloc);
            c1b.setText(doloc);
            c1c.setText(putime);
            c1d.setText(dotime);
            c1e.setText(car);
            c1f.setText("Rs "+hourlyprice);
            c2a.setText(fn);
            c2b.setText(ln);
            c2c.setText(contact);
            c2d.setText(email);
            c3a.setText(paymethod);
            c3b.setText(cardno);
            c3c.setText(cardname);
            c3d.setText(billadd);
            c3e.setText(billcity);
            c4.setText("Rs "+grandtotal);
        }
    }//GEN-LAST:event_mainbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton OKBtn;
    private javax.swing.JLabel c1a;
    private javax.swing.JLabel c1b;
    private javax.swing.JLabel c1c;
    private javax.swing.JLabel c1d;
    private javax.swing.JLabel c1e;
    private javax.swing.JLabel c1f;
    private javax.swing.JLabel c2a;
    private javax.swing.JLabel c2b;
    private javax.swing.JLabel c2c;
    private javax.swing.JLabel c2d;
    private javax.swing.JLabel c3a;
    private javax.swing.JLabel c3b;
    private javax.swing.JLabel c3c;
    private javax.swing.JLabel c3d;
    private javax.swing.JLabel c3e;
    private javax.swing.JLabel c4;
    private javax.swing.JButton mainbtn;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JTextField maintf;
    private javax.swing.JLabel tf1;
    private javax.swing.JLabel tf10;
    private javax.swing.JLabel tf11;
    private javax.swing.JLabel tf12;
    private javax.swing.JLabel tf13;
    private javax.swing.JLabel tf14;
    private javax.swing.JLabel tf15;
    private javax.swing.JLabel tf16;
    private javax.swing.JLabel tf17;
    private javax.swing.JLabel tf18;
    private javax.swing.JLabel tf19;
    private javax.swing.JLabel tf2;
    private javax.swing.JLabel tf20;
    private javax.swing.JLabel tf21;
    private javax.swing.JLabel tf22;
    private javax.swing.JLabel tf3;
    private javax.swing.JLabel tf4;
    private javax.swing.JLabel tf5;
    private javax.swing.JLabel tf6;
    private javax.swing.JLabel tf7;
    private javax.swing.JLabel tf8;
    private javax.swing.JLabel tf9;
    // End of variables declaration//GEN-END:variables
}
