/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ahuja
 */
public class Frame3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
        for(int i=0;i<17;i++){
            maintable1.getColumnModel().getColumn(i).setPreferredWidth(200);}
        String user="";
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from signedin;";
            ResultSet rs = stmt.executeQuery(q);
            if(rs.next()) {
                user=rs.getString(1);
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity (signedin)");
        }
        DefaultTableModel model = (DefaultTableModel) maintable1.getModel();
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from admin where username='"+user+"';";
            ResultSet rs = stmt.executeQuery(q);
            while(rs.next()) {
                model.addRow(new Object[] {
                    rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(6),
                    rs.getFloat(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),
                    rs.getString(13),rs.getString(14),rs.getString(15),rs.getString(16),rs.getString(17),rs.getFloat(18)                
                });
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity (admin)");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainscroll1 = new javax.swing.JScrollPane();
        maintable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(728, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here Are Your Bookings:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 260, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Luxor Luxury Car Rentals");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        mainscroll1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        maintable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pick Up Location", "Drop Off Location", "Pick Up Time   ", "Drop Off Time", "Selected Car", "Hourly Price", "First Name", "Last Name", "Contact", "Email", "Payment Method", "Card Number", "Cardholder Name", "Billing Address", "Billing City", "Luxor Code", "Grand Total"
            }
        ));
        maintable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        mainscroll1.setViewportView(maintable1);

        getContentPane().add(mainscroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 660, 140));

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 240, -1));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg2.jpg")); // NOI18N
        BGLabel.setPreferredSize(new java.awt.Dimension(728, 400));
        getContentPane().add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 729, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane mainscroll1;
    private javax.swing.JTable maintable1;
    // End of variables declaration//GEN-END:variables
}
