/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;
import MyFrames.MyPanels.Panel1;
import MyFrames.MyPanels.Panel2;
import MyFrames.MyPanels.Panel3;
import MyFrames.MyPanels.Panel4;
import MyFrames.MyPanels.Panel5;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
/**
 *
 * @author Ahuja
 */
public class Frame1 extends javax.swing.JInternalFrame {
    GridBagLayout layout = new GridBagLayout();
    Panel1 p1;
    Panel2 p2;
    Panel3 p3;
    Panel4 p4;
    Panel5 p5;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        p1 = new Panel1();
        p2 = new Panel2();
        p3 = new Panel3();
        p4 = new Panel4();
        p5 = new Panel5();
        
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy=0;
        DynamicPanel.add(p1,c);
        c.gridx = 0;
        c.gridy=0;
        DynamicPanel.add(p2,c);
        c.gridx = 0;
        c.gridy=0;
        DynamicPanel.add(p3,c);
        c.gridx = 0;
        c.gridy=0;
        DynamicPanel.add(p4,c);
        c.gridx = 0;
        c.gridy=0;
        DynamicPanel.add(p5,c);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelButtons = new javax.swing.JPanel();
        BtnPanel1 = new javax.swing.JButton();
        BtnPanel2 = new javax.swing.JButton();
        BtnPanel3 = new javax.swing.JButton();
        BtnPanel4 = new javax.swing.JButton();
        BtnPanel5 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Book A Car");
        setPreferredSize(new java.awt.Dimension(728, 400));

        PanelButtons.setBackground(new java.awt.Color(102, 0, 102));

        BtnPanel1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        BtnPanel1.setForeground(new java.awt.Color(102, 0, 102));
        BtnPanel1.setText("Customer Input");
        BtnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel1ActionPerformed(evt);
            }
        });

        BtnPanel2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        BtnPanel2.setForeground(new java.awt.Color(102, 0, 102));
        BtnPanel2.setText("Car Select");
        BtnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel2ActionPerformed(evt);
            }
        });

        BtnPanel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        BtnPanel3.setForeground(new java.awt.Color(102, 0, 102));
        BtnPanel3.setText("Review Info");
        BtnPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel3ActionPerformed(evt);
            }
        });

        BtnPanel4.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        BtnPanel4.setForeground(new java.awt.Color(102, 0, 102));
        BtnPanel4.setText("Personal Info");
        BtnPanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel4ActionPerformed(evt);
            }
        });

        BtnPanel5.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        BtnPanel5.setForeground(new java.awt.Color(102, 0, 102));
        BtnPanel5.setText("Payment Screen");
        BtnPanel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanel5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonsLayout = new javax.swing.GroupLayout(PanelButtons);
        PanelButtons.setLayout(PanelButtonsLayout);
        PanelButtonsLayout.setHorizontalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addComponent(BtnPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelButtonsLayout.setVerticalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(PanelButtons, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setBackground(new java.awt.Color(51, 0, 51));
        DynamicPanel.setPreferredSize(new java.awt.Dimension(597, 400));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel1ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);        
    }//GEN-LAST:event_BtnPanel1ActionPerformed

    private void BtnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel2ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);        
    }//GEN-LAST:event_BtnPanel2ActionPerformed

    private void BtnPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel3ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_BtnPanel3ActionPerformed

    private void BtnPanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel4ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);        
    }//GEN-LAST:event_BtnPanel4ActionPerformed

    private void BtnPanel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanel5ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);      
    }//GEN-LAST:event_BtnPanel5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPanel1;
    public javax.swing.JButton BtnPanel2;
    public javax.swing.JButton BtnPanel3;
    public javax.swing.JButton BtnPanel4;
    public javax.swing.JButton BtnPanel5;
    private javax.swing.JPanel DynamicPanel;
    public javax.swing.JPanel PanelButtons;
    // End of variables declaration//GEN-END:variables
}
