
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahuja
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fntf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lntf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        warnlabel5 = new javax.swing.JLabel();
        warnlabel4 = new javax.swing.JLabel();
        warnlabel3 = new javax.swing.JLabel();
        warnlabel2 = new javax.swing.JLabel();
        warnlabel1 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contacttf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        createpwdtf = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        confirmpwdtf = new javax.swing.JPasswordField();
        termscb = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("and must be between 5 and 15 characters.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jButton2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 51));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 130, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Luxor Luxury Car Rentals");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Confirm Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Signup");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        usernametf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        usernametf.setForeground(new java.awt.Color(51, 0, 51));
        usernametf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernametfFocusGained(evt);
            }
        });
        usernametf.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                usernametfInputMethodTextChanged(evt);
            }
        });
        usernametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametfActionPerformed(evt);
            }
        });
        usernametf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                usernametfPropertyChange(evt);
            }
        });
        usernametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernametfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernametfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernametfKeyTyped(evt);
            }
        });
        getContentPane().add(usernametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 250, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*First Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        fntf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        fntf.setForeground(new java.awt.Color(51, 0, 51));
        fntf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fntfKeyTyped(evt);
            }
        });
        getContentPane().add(fntf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 250, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*Last Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        lntf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lntf.setForeground(new java.awt.Color(51, 0, 51));
        lntf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lntfKeyTyped(evt);
            }
        });
        getContentPane().add(lntf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 250, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fill In All The Fields Marked With *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Passwords Should Be Atleast 8 Characters.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*User Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        warnlabel5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        getContentPane().add(warnlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 250, 20));

        warnlabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        getContentPane().add(warnlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 250, 20));

        warnlabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        getContentPane().add(warnlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 250, 20));

        warnlabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        getContentPane().add(warnlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 310, 20));

        warnlabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        getContentPane().add(warnlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 250, 20));

        emailtf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        emailtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailtfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailtfKeyTyped(evt);
            }
        });
        getContentPane().add(emailtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 310, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Email:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username can contain alphabets and numbers");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        contacttf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        contacttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contacttfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contacttfKeyTyped(evt);
            }
        });
        getContentPane().add(contacttf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 250, -1));

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("*Contact:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        createpwdtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                createpwdtfKeyReleased(evt);
            }
        });
        getContentPane().add(createpwdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 250, 30));

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*Create Password:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        confirmpwdtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmpwdtfKeyReleased(evt);
            }
        });
        getContentPane().add(confirmpwdtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 250, 30));

        termscb.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        termscb.setForeground(new java.awt.Color(255, 255, 255));
        termscb.setText("I Accept The Terms & Conditions Of Luxor Car Rentals");
        termscb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termscbActionPerformed(evt);
            }
        });
        getContentPane().add(termscb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 450, -1));

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg2.jpg")); // NOI18N
        BGLabel.setPreferredSize(new java.awt.Dimension(500, 650));
        getContentPane().add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int u1=0;
    int u2=0;
    int u3=0;
    int u4=0;
    int u5=0;
    int u6=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usernametfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametfKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isLetterOrDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume(); }
        if (usernametf.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_usernametfKeyTyped

    private void usernametfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_usernametfPropertyChange
        // TODO add your handling code here:       
        
    }//GEN-LAST:event_usernametfPropertyChange

    private void usernametfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametfFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernametfFocusGained

    private void usernametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametfActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_usernametfActionPerformed

    private void usernametfInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_usernametfInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametfInputMethodTextChanged

    private void usernametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametfKeyPressed
  
    }//GEN-LAST:event_usernametfKeyPressed

    private void usernametfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametfKeyReleased
        // TODO add your handling code here:
        if (!(usernametf.getText().equals(""))) {
            if (usernametf.getText().length()>=5) {
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from login;";
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()) {
                if (usernametf.getText().equals(rs.getString(3))) {
                    u1=0;
                    break;
                }
                else {
                    u1=1;
                }
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        if (u1==1) {
            warnlabel1.setForeground(Color.green);
            warnlabel1.setText("Username Correct");
        }
        else {
            u1=0;
            warnlabel1.setForeground(Color.red);
            warnlabel1.setText("Username Already Taken");
        } }
            else { 
                u1=0;
                warnlabel1.setForeground(Color.red);
                warnlabel1.setText("Atleast 5 Characters");
            }
        }
        else {
            u1=0;
            warnlabel1.setForeground(Color.red);
            warnlabel1.setText("This Field Cannot Be Left Blank");
        }
    }//GEN-LAST:event_usernametfKeyReleased

    private void fntfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fntfKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume(); }
    }//GEN-LAST:event_fntfKeyTyped

    private void lntfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lntfKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume(); }        
    }//GEN-LAST:event_lntfKeyTyped

    private void emailtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtfKeyReleased
        // TODO add your handling code here:
        if (emailtf.getText().contains("@") && emailtf.getText().contains(".")) {
            u2=1;
            warnlabel2.setForeground(Color.GREEN);
            warnlabel2.setText("Email Correct");
        }
        else {
            u2=0;
            warnlabel2.setForeground(Color.RED);
            warnlabel2.setText("Enter A Valid Email Address");
        }
    }//GEN-LAST:event_emailtfKeyReleased

    private void contacttfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttfKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            evt.consume(); }        
    }//GEN-LAST:event_contacttfKeyTyped

    private void contacttfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttfKeyReleased
        // TODO add your handling code here:
        if (contacttf.getText().length()==10) {
            u3=1;
            warnlabel3.setForeground(Color.GREEN);
            warnlabel3.setText("Contact Correct");
        }
        else {
            u3=0;
            warnlabel3.setForeground(Color.RED);
            warnlabel3.setText("Number Should Be 10 Digits");
        }
    }//GEN-LAST:event_contacttfKeyReleased

    private void createpwdtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createpwdtfKeyReleased
        // TODO add your handling code here:
        String pwd = new String(createpwdtf.getPassword());
        if (pwd.length()>=8) {
            u4=1;
            warnlabel4.setForeground(Color.GREEN);
            warnlabel4.setText("Password Correct");
        }
        else {
            u4=0;
            warnlabel4.setForeground(Color.RED);
            warnlabel4.setText("Atleast 8 Characters");
        }
    }//GEN-LAST:event_createpwdtfKeyReleased

    private void emailtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtfKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c==' ') {
            evt.consume();
        }
    }//GEN-LAST:event_emailtfKeyTyped

    private void confirmpwdtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpwdtfKeyReleased
        // TODO add your handling code here:
        String pwd = new String(createpwdtf.getPassword());
        String cpwd = new String(confirmpwdtf.getPassword());
        if (u4==1) { 
        if (pwd.equals(cpwd)) {
            u5=1;
            warnlabel5.setForeground(Color.GREEN);
            warnlabel5.setText("Passwords Match");
        }
        else {
            u5=0;
            warnlabel5.setForeground(Color.RED);
            warnlabel5.setText("Passwords Do Not Match");
        } }
        else {
            warnlabel5.setForeground(Color.RED);
            warnlabel5.setText("Create A Valid Password First");
        }
    }//GEN-LAST:event_confirmpwdtfKeyReleased

    private void termscbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termscbActionPerformed
        // TODO add your handling code here:
        if (termscb.isSelected()) {
            u6=1;
        }
        else {
            u6=0;
        }
    }//GEN-LAST:event_termscbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pwd = new String(createpwdtf.getPassword());
        String cpwd = new String(confirmpwdtf.getPassword());
        if (!(fntf.getText().equals("") || lntf.getText().equals("") || usernametf.getText().equals("")
                || emailtf.getText().equals("") || contacttf.getText().equals("")
                || pwd.equals("") || cpwd.equals("")  )) {
                   if (!(u1==0 || u2==0 || u3==0 || u4==0 || u5==0)) {
                       if (!(u6==0)) {
                           try {
                               Class.forName("java.sql.Driver");
                               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
                               Statement stmt = con.createStatement();
                               String q = "insert into login values('"+fntf.getText()+"','"+lntf.getText()+"','"+usernametf.getText()+"','"
                                       +cpwd+"','"+emailtf.getText()+"','"+contacttf.getText()+"');";
                               int rs = stmt.executeUpdate(q);
                               stmt.close();
                               con.close();
                               this.dispose();
                               JOptionPane.showMessageDialog(null,"Account Successfully Created.\nPlease Login.","Welcome",JOptionPane.INFORMATION_MESSAGE);
                           }
                           catch (Exception e) {
                               JOptionPane.showMessageDialog(null,"Error In Connectivity");
                           }
                       }
                       else {
                           JOptionPane.showMessageDialog(null,"Please Accept The\nTerms And Conditions","Error",JOptionPane.ERROR_MESSAGE);
                       }
                   }
                   else {
                       JOptionPane.showMessageDialog(null,"Please Correct All The Errors\nMarked In Red","Error",JOptionPane.ERROR_MESSAGE);
                   }
        }
        else {
            JOptionPane.showMessageDialog(null,"Please Fill In All The Fields","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JPasswordField confirmpwdtf;
    private javax.swing.JTextField contacttf;
    private javax.swing.JPasswordField createpwdtf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField fntf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lntf;
    private javax.swing.JCheckBox termscb;
    private javax.swing.JTextField usernametf;
    private javax.swing.JLabel warnlabel1;
    private javax.swing.JLabel warnlabel2;
    private javax.swing.JLabel warnlabel3;
    private javax.swing.JLabel warnlabel4;
    private javax.swing.JLabel warnlabel5;
    // End of variables declaration//GEN-END:variables
}
