/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.*;

/**
 *
 * @author Ahuja
 */
public class Panel1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public Panel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        dotf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        putf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dod2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dod1 = new javax.swing.JComboBox<>();
        pud1 = new javax.swing.JComboBox<>();
        dot2 = new javax.swing.JComboBox<>();
        pud2 = new javax.swing.JComboBox<>();
        dot1 = new javax.swing.JComboBox<>();
        put1 = new javax.swing.JComboBox<>();
        put2 = new javax.swing.JComboBox<>();
        OKBtn = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 0));
        setPreferredSize(new java.awt.Dimension(597, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        dotf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        add(dotf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 400, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pick Up:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        putf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        add(putf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 400, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Drop Off:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Drop-Off Date:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        dod2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        dod2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(dod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 50, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pick-Up Date:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        dod1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        dod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan 2017", "Feb 2017", "March 2017", "April 2017", "May 2017", "June 2017", "July 2017", "Aug 2017", "Sept 2017", "Oct 2017", "Nov 2017", "Dec 2017" }));
        add(dod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, -1));

        pud1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        pud1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan 2017", "Feb 2017", "March 2017", "April 2017", "May 2017", "June 2017", "July 2017", "Aug 2017", "Sept 2017", "Oct 2017", "Nov 2017", "Dec 2017" }));
        add(pud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        dot2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        dot2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        add(dot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 50, -1));

        pud2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        pud2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(pud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 50, -1));

        dot1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        dot1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(dot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 50, -1));

        put1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        put1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(put1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 50, -1));

        put2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        put2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        add(put2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 50, -1));

        OKBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        OKBtn.setForeground(new java.awt.Color(102, 0, 102));
        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });
        add(OKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 170, 40));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg.jpg")); // NOI18N
        BGLabel.setPreferredSize(new java.awt.Dimension(597, 404));
        add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        // TODO add your handling code here:
        String pul = putf.getText();
        String dol = dotf.getText();
        String use1 = (String) pud1.getSelectedItem();
        String use2= (String) pud2.getSelectedItem();
        String pud = use2+" "+use1;
        String use3 = (String) put1.getSelectedItem();
        String use4 = (String) put2.getSelectedItem();
        String put = use3+":"+use4;
        String use5 = (String) dod1.getSelectedItem();
        String use6 = (String) dod2.getSelectedItem();
        String dod = use6+" "+use5;
        String use7 = (String) dot1.getSelectedItem();
        String use8 = (String) dot2.getSelectedItem();
        String dot = use7+":"+use8;
        String pumonth="";
        String domonth="";
        
        //Total Time Calculator
        if(use1=="Jan 2017"){
            pumonth="01";
        }
        else if(use1=="Feb 2017") {
            pumonth="02";
        }
        else if(use1=="March 2017") {
            pumonth="03";
        }
        else if(use1=="April 2017") {
            pumonth="02";
        }
        else if(use1=="May 2017") {
            pumonth="05";
        }
        else if(use1=="June 2017") {
            pumonth="06";
        }
        else if(use1=="July 2017") {
            pumonth="07";
        }
        else if(use1=="Aug 2017") {
            pumonth="08";
        }
        else if(use1=="Sept 2017") {
            pumonth="09";
        }
        else if(use1=="Oct 2017") {
            pumonth="10";
        }
        else if(use1=="Nov 2017") {
            pumonth="11";
        }
        else {
            pumonth="12";
        }
        
        
        if(use5=="Jan 2017"){
            domonth="01";
        }
        else if(use5=="Feb 2017") {
            domonth="02";
        }
        else if(use5=="March 2017") {
            domonth="03";
        }
        else if(use5=="April 2017") {
            domonth="02";
        }
        else if(use5=="May 2017") {
            domonth="05";
        }
        else if(use5=="June 2017") {
            domonth="06";
        }
        else if(use5=="July 2017") {
            domonth="07";
        }
        else if(use5=="Aug 2017") {
            domonth="08";
        }
        else if(use5=="Sept 2017") {
            domonth="09";
        }
        else if(use5=="Oct 2017") {
            domonth="10";
        }
        else if(use5=="Nov 2017") {
            domonth="11";
        }
        else {
            domonth="12";
        }
    String pickupd= "2017-"+pumonth+"-"+use2;
    String dropoffd= "2017-"+domonth+"-"+use6;
    System.out.println(pickupd+" "+dropoffd);
    int a = Integer.parseInt(use2);
    int b = Integer.parseInt(pumonth);
    int c = Integer.parseInt(use6);
    int d = Integer.parseInt(domonth);
    Date pickupdate = new Date(17,b,a);
    Date dropoffdate = new Date(17,d,c);
    long diff = (dropoffdate.getTime() - pickupdate.getTime())-86400000;
    System.out.println(""+diff); 
    int pickupmin = (24-Integer.parseInt(use3))*60+(60-Integer.parseInt(use4));
    int dropoffmin = (Integer.parseInt(use7))*60+Integer.parseInt(use8);
    float totalminutes = (diff/60000)+pickupmin+dropoffmin;
    float totalhoursmain = (totalminutes/60)-1;
    System.out.println(""+totalhoursmain);
    
    

        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "insert into screen1 values('"+pul+"'"+","+"'"+dol+"'"+","+"'"+pud+"'"+","+"'"+put+"'"+","+"'"+
                    dod+"'"+","+"'"+dot+"'"+","+totalhoursmain+");";
            System.out.println(q);
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        OKBtn.setVisible(false);
        putf.setEnabled(false);
        dotf.setEnabled(false);
        dod1.setEnabled(false);
        dod2.setEnabled(false);
        pud1.setEnabled(false);
        pud2.setEnabled(false);
        dot1.setEnabled(false);
        dot2.setEnabled(false);
        put1.setEnabled(false);
        put2.setEnabled(false);
    }//GEN-LAST:event_OKBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton OKBtn;
    private javax.swing.JComboBox<String> dod1;
    private javax.swing.JComboBox<String> dod2;
    private javax.swing.JComboBox<String> dot1;
    private javax.swing.JComboBox<String> dot2;
    private javax.swing.JTextField dotf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> pud1;
    private javax.swing.JComboBox<String> pud2;
    private javax.swing.JComboBox<String> put1;
    private javax.swing.JComboBox<String> put2;
    private javax.swing.JTextField putf;
    // End of variables declaration//GEN-END:variables
}
