/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;
import MyFrames.MyPanels.CVV;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;
/**
 *
 * @author Ahuja
 */
public class Panel5 extends javax.swing.JPanel {

    /**
     * Creates new form Panel5
     */
    public Panel5() {
        initComponents();
        motiontf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        american = new javax.swing.JRadioButton();
        master = new javax.swing.JRadioButton();
        visa = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf3b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3a = new javax.swing.JTextField();
        motiontf = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        PayBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BGLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(729, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("*Billing Address:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Screen");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        buttonGroup1.add(american);
        american.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        american.setForeground(new java.awt.Color(255, 255, 255));
        american.setText("American Express");
        american.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanActionPerformed(evt);
            }
        });
        add(american, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        buttonGroup1.add(master);
        master.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        master.setForeground(new java.awt.Color(255, 255, 255));
        master.setText("MasterCard");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });
        add(master, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        buttonGroup1.add(visa);
        visa.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        visa.setForeground(new java.awt.Color(255, 255, 255));
        visa.setText("Visa");
        visa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaActionPerformed(evt);
            }
        });
        add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 3, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("You must fill in all the fields marked with *");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Payment Method:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        tf3b.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        add(tf3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 30, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Card Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("CVV?");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 50, 30));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        tf2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 60, -1));

        tf3a.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        add(tf3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 30, -1));

        motiontf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        motiontf.setForeground(new java.awt.Color(255, 255, 255));
        add(motiontf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 340, 30));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("*Expiry Date:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        tf1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 340, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*Card Holder Name:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        tf4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 340, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*CVV:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        cb1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(51, 0, 51));
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bairagarh", "Bhopal", "Indore", "Jabalpur", "Gwalior" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("*City:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        tf5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 340, -1));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextField8.setText("Madhya Pradesh, India");
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 340, -1));

        PayBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        PayBtn.setForeground(new java.awt.Color(51, 0, 51));
        PayBtn.setText("Pay");
        PayBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PayBtnMouseMoved(evt);
            }
        });
        PayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBtnActionPerformed(evt);
            }
        });
        add(PayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, 520, 40));

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("*State & Country:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*Contact and Email:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg2.jpg")); // NOI18N
        BGLabel.setPreferredSize(new java.awt.Dimension(729, 400));
        add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));
    }// </editor-fold>//GEN-END:initComponents
    
    Random hh = new Random();
    int aa;
    String cc="";
    public class StartOfProg {
    public String starters() {
    for(int count=1;count<8;count++) {
        aa = 1+hh.nextInt(9);
        cc+=aa;
       }
    return("LXR"+cc);
   }
    }
   StartOfProg bb = new StartOfProg();
   String CODE=bb.starters();     
    String paymethod="";
    String contact="";
    String email="";
    String city = "Bairagarh";
    String cardno = "";
    String cvv = "";
    String mm = "";
    String yy = "";
    String cardname="";
    String billadd="";
    String username="";
    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
        if (master.isSelected()) {
            paymethod="MasterCard";
            System.out.println(paymethod);
        } 
    }//GEN-LAST:event_masterActionPerformed

    private void visaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaActionPerformed
        // TODO add your handling code here:
        if (visa.isSelected()) {
            paymethod="Visa";
            System.out.println(paymethod);
    }//GEN-LAST:event_visaActionPerformed
    }
    private void americanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanActionPerformed
        // TODO add your handling code here:
        if (american.isSelected()) {
            paymethod="American Express";
            System.out.println(paymethod);
    }//GEN-LAST:event_americanActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CVV obj = new CVV();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PayBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayBtnMouseMoved
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from screen3;";
            ResultSet rs = stmt.executeQuery(q);
            if(rs.next()){
                contact = rs.getString(3);
                email = rs.getString(4);
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        motiontf.setText(" "+contact+" "+email);
        motiontf.setVisible(true);
    }//GEN-LAST:event_PayBtnMouseMoved

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        city = (String) cb1.getSelectedItem();
        System.out.println(city);
    }//GEN-LAST:event_cb1ActionPerformed

    private void PayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBtnActionPerformed
        // TODO add your handling code here:
        cardno = tf1.getText();
        cvv = tf2.getText();
        mm = tf3a.getText();
        yy = tf3b.getText();
        cardname = tf4.getText();
        billadd = tf5.getText();
        if (paymethod=="" || cardno.length()!=16 || Pattern.matches("[a-zA-Z]+", cardno) == true || cvv.length()!=3 
                || Pattern.matches("[a-zA-Z]+", cvv) == true || mm.length()!=2
                || Pattern.matches("[a-zA-Z]+", mm) == true || yy.length()!=2
                || Pattern.matches("[a-zA-Z]+", yy) == true || Integer.parseInt(yy)>=18==false
                || cardname.equals("") || billadd.equals("")){
            JOptionPane.showMessageDialog(null,"ERROR: Please check your details");
            //if(Integer.parseInt(yy)>=18==false) {
              //  JOptionPane.showMessageDialog(null,"ERROR: Card Expiry Date Should Be\nAtleast 18.");
            //}
           
            
        }
        else {
        int reply = JOptionPane.showConfirmDialog(null, "Confirm Payment?", "Confirm Payment", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
          String abcd = "XXXXXXXXXXXX"+cardno.substring(12,16);
          System.out.println(abcd);
          
          try{
              Class.forName("java.sql.Driver");
              Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
              Statement stmt = con.createStatement();
              String q = "insert into screen4 values('"+paymethod+"','"+abcd+"','"+cardname+"','"+billadd+"','"+city+"','"+CODE+"');";
              int rs = stmt.executeUpdate(q);
              System.out.println(q);
              stmt.close();
              con.close();
              PayBtn.setVisible(false);
              master.setEnabled(false);
              visa.setEnabled(false);
              american.setEnabled(false);
              tf1.setEnabled(false);
              tf2.setEnabled(false);
              tf3a.setEnabled(false);
              tf3b.setEnabled(false);
              tf4.setEnabled(false);
              tf5.setEnabled(false);
              cb1.setEnabled(false);
              System.out.println(CODE);
              JOptionPane.showMessageDialog(null,"Thank You For Your Booking.\nHere Is Your Luxor Code:\n"+CODE+"\n-Luxor Luxury Car Rentals");
              String puloc="";
              String doloc="";
              String inserttime1="";
              String inserttime2="";
              float noofhours=0;
              String selectedcar="";
              float hourlyprice=0;
              String firstname="";
              String lastname="";
              float grandtotal=0;
              try {
                  Class.forName("java.sql.Driver");
                  Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
                  Statement stmt1 = con1.createStatement();
                  String q1 = "select * from screen1;";
                  ResultSet rs1 = stmt1.executeQuery(q1);
                  if(rs1.next()) {
                      puloc = rs1.getString(1);
                      doloc = rs1.getString(2);
                      inserttime1 = rs1.getString(3)+" "+rs1.getString(4);
                      inserttime2 = rs1.getString(5)+" "+rs1.getString(6);
                      noofhours = rs1.getFloat(7);
                  }
                  rs1.close();
                  stmt1.close();
                  con1.close();
              }
              catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Error in connectivity (Screen1)");
              }
              try {
                  Class.forName("java.sql.Driver");
                  Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
                  Statement stmt1 = con1.createStatement();
                  String q1 = "select * from screen2;";
                  ResultSet rs1 = stmt1.executeQuery(q1);
                  if(rs1.next()) {
                      selectedcar = rs1.getString(1);
                      hourlyprice = rs1.getFloat(2);
                  }
                  rs1.close();
                  stmt1.close();
                  con1.close();
              }
              catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Error in connectivity (Screen2)");
              } 
              try {
                  Class.forName("java.sql.Driver");
                  Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
                  Statement stmt1 = con1.createStatement();
                  String q1 = "select * from screen3;";
                  ResultSet rs1 = stmt1.executeQuery(q1);
                  if(rs1.next()) {
                      firstname = rs1.getString(1);
                      lastname = rs1.getString(2);
                  }
                  rs1.close();
                  stmt1.close();
                  con1.close();
              }
              catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Error in connectivity (Screen3)");
              } 
              try {
                  Class.forName("java.sql.Driver");
                  Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
                  Statement stmt1 = con1.createStatement();
                  String q1 = "select * from signedin;";
                  ResultSet rs1 = stmt1.executeQuery(q1);
                  if (rs1.next()) {
                      username = rs1.getString(1);
                  }
                  rs1.close();
                  stmt1.close();
                  con1.close();
              }
              catch(Exception e) {
                  JOptionPane.showMessageDialog(null,"Error in connectivity (signedin)");
              }
              //Delete Insert In Admin cal grandtotal
              try {
                  String cardnum = "XXXXXXXXXXXX"+cardno.substring(12,16);
                  float grand_total = noofhours * hourlyprice; 
                  Class.forName("java.sql.Driver");
                  Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
                  Statement stmt1 = con1.createStatement();
                  String q1 = "insert into admin values('"+puloc+"','"+doloc+"','"+inserttime1+"','"+inserttime2
                          +"',"+noofhours+",'"+selectedcar+"',"+hourlyprice+",'"+firstname+"','"+lastname+"','"
                          +contact+"','"+email+"','"+paymethod+"','"+cardnum+"','"+cardname+"','"+billadd+"','"
                          +city+"','"+CODE+"',"+grand_total+",'"+username+"');";
                  int rs1 = stmt1.executeUpdate(q1);
                  stmt1.close();
                  con1.close();
                  System.out.println(q1);
              }
              catch(Exception e){
                  JOptionPane.showMessageDialog(null,"Error in connectivity (Admin)");
              }
        try {
            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt1 = con1.createStatement();
            String q1 = "delete from screen1;";
            int rs1 = stmt1.executeUpdate(q1);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Deletion Screen1");
        }
        try {
            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt1 = con1.createStatement();
            String q1 = "delete from screen2;";
            int rs1 = stmt1.executeUpdate(q1);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Deletion Screen2");
        } 
        try {
            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt1 = con1.createStatement();
            String q1 = "delete from screen3;";
            int rs1 = stmt1.executeUpdate(q1);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Deletion Screen3");
        }        
        try {
            Class.forName("java.sql.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt1 = con1.createStatement();
            String q1 = "delete from screen4;";
            int rs1 = stmt1.executeUpdate(q1);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Deletion Screen4");
        }              
              
              
              
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(null,"Error In Connectivity");
          }
        }
        else {
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from screen1;";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from screen2;";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from screen3;";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        System.exit(0);
        }
        }
    }//GEN-LAST:event_PayBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton PayBtn;
    private javax.swing.JRadioButton american;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JRadioButton master;
    private javax.swing.JLabel motiontf;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3a;
    private javax.swing.JTextField tf3b;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JRadioButton visa;
    // End of variables declaration//GEN-END:variables
}
