/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Ahuja
 */
public class Panel2 extends javax.swing.JPanel {

    /**
     * Creates new form Panel2
     */
    public Panel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        carlabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        OKBtn = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(597, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(carlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Lexus LX 570");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Mercedes G63 AMG");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Land Rover Range Rover");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("BMW X6");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Limousine:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUV:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 50, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Maserati GranTurismo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Lexus LS460");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Maybach");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Mercedes S500");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Lamborghini Aventador");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Bentley Mulsanne");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Ferrari 458");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("Aston Martin DB9");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Luxury Car:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sports Car:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 130, -1));

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("Limo 2");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Limo 1");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        OKBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        OKBtn.setForeground(new java.awt.Color(102, 0, 102));
        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });
        add(OKBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 540, -1));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg.jpg")); // NOI18N
        BGLabel.setPreferredSize(new java.awt.Dimension(597, 404));
        add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));
    }// </editor-fold>//GEN-END:initComponents

    String SelectedCar="";
    float HourlyPrice=0;
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Lexus LX570";
        HourlyPrice=925;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton3.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc4.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Mercedes G63 AMG";
        HourlyPrice=1205;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton3ActionPerformed
    }
    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton4.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc2.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Land Rover Range Rover";
        HourlyPrice=1205;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    }
    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton5.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc3.gif");
        carlabel.setIcon(newimg);
        SelectedCar="BMW X6";
        HourlyPrice=650;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton5ActionPerformed
    }
    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton8.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc6.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Mercedes S500";
        HourlyPrice=1385;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton8ActionPerformed
    }
    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton7.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc8.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Maybach S600";
        HourlyPrice=2590;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton7ActionPerformed
    }
    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton10.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc7.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Bentley Mulsanne";
        HourlyPrice=3240;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton10ActionPerformed
    }
    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton6.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc5.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Lexus LS460";
        HourlyPrice=1295;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);  
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton6ActionPerformed
    }
    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton12.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc10.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Aston Martin DB9";
        HourlyPrice=1945;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);  
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton12ActionPerformed
    }
    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton11.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc11.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Ferrari 458";
        HourlyPrice=2500;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);   
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton11ActionPerformed
    }
    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton9.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc9.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Lamborghini Aventador";
        HourlyPrice=2775;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);    
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton9ActionPerformed
    }
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\pc12.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Maserati GranTurismo";
        HourlyPrice=1850;
        JOptionPane.showMessageDialog(null,"Selected Vehicle: "+SelectedCar+"\n"+"Price Per Hour For This Vehicle Is: Rs "+HourlyPrice);
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    }
    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton14.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\limo.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Dodge Charger Limousine";
        HourlyPrice=15725;
        JOptionPane.showMessageDialog(null,"INFO: Limousine Comes With A Compulsory Driver."+"\n\n"+"Selected Limousine: "+SelectedCar+"\n"+"Price Per Hour For This Limousine Is: Rs "+HourlyPrice);   
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton14ActionPerformed
    }
    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton13.isSelected()==true) {
        ImageIcon newimg= new ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\limo2.gif");
        carlabel.setIcon(newimg);
        SelectedCar="Hummer H2 Limousine";
        HourlyPrice=18000;
        JOptionPane.showMessageDialog(null,"INFO: Limousine Comes With A Compulsory Driver."+"\n\n"+"Selected Limousine: "+SelectedCar+"\n"+"Price Per Hour For This Limousine Is: Rs "+HourlyPrice);  
        System.out.println(SelectedCar);
    }//GEN-LAST:event_jRadioButton13ActionPerformed
    }
    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "insert into screen2 values('"+SelectedCar+"',"+HourlyPrice+");";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        OKBtn.setVisible(false);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton10.setEnabled(false);
        jRadioButton11.setEnabled(false);
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        jRadioButton14.setEnabled(false);        
    }//GEN-LAST:event_OKBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton OKBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel carlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
