/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahuja
 */
public class Panel3 extends javax.swing.JPanel {

    /**
     * Creates new form Panel3
     */
    public Panel3() {
        initComponents();
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);  
        termscb.setVisible(false);
        yesbtn.setVisible(false);
        nobtn.setVisible(false);
        //Frame1 obj= new Frame1();
        //obj.PanelButtons.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        termscb = new javax.swing.JCheckBox();
        nobtn = new javax.swing.JButton();
        yesbtn = new javax.swing.JButton();
        BGLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(729, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 350, 40));

        l5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("Grand Total:");
        add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 40));

        l1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Rental Date:");
        add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 40));

        label2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 350, 40));

        l2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Return Date:");
        add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 40));

        label3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 350, 40));

        l3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Vehicle:");
        add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 40));

        label4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 350, 40));

        jButton1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("View Your Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 111, 470, 70));

        l4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Hourly Rent:");
        add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 40));

        label5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 350, 40));

        termscb.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        termscb.setForeground(new java.awt.Color(255, 255, 255));
        termscb.setText("I Accept The Terms And Conditions Of Luxor Luxury Car Rentals. ");
        termscb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termscbActionPerformed(evt);
            }
        });
        add(termscb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        nobtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        nobtn.setForeground(new java.awt.Color(102, 0, 102));
        nobtn.setText("No, Exit");
        nobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobtnActionPerformed(evt);
            }
        });
        add(nobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 180, -1));

        yesbtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        yesbtn.setForeground(new java.awt.Color(102, 0, 102));
        yesbtn.setText("Yes, Continue");
        yesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesbtnActionPerformed(evt);
            }
        });
        add(yesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        BGLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahuja\\Desktop\\Project\\Pictures\\bg2.jpg")); // NOI18N
        BGLabel.setPreferredSize(new java.awt.Dimension(729, 400));
        add(BGLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));
    }// </editor-fold>//GEN-END:initComponents

        String date1="";
        String date2="";
        String vehi="";
        float hourlyrent=0;
        float hoursno=0;
        float grandtotal=0;
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(false);
        l1.setVisible(true);
        l2.setVisible(true);
        l3.setVisible(true);
        l4.setVisible(true);
        l5.setVisible(true);
        termscb.setVisible(true);
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from screen1;";
            ResultSet rs = stmt.executeQuery(q);
            if(rs.next()){
                date1=rs.getString(3)+" "+rs.getString(4);
                date2=rs.getString(5)+" "+rs.getString(6);
                hoursno = rs.getFloat(7);
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "select * from screen2;";
            ResultSet rs = stmt.executeQuery(q);
            if (rs.next()) {
                vehi = rs.getString(1);
                hourlyrent = rs.getFloat(2);
                rs.close();
                stmt.close();
                con.close();
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        grandtotal = hourlyrent * hoursno;
        label2.setText(date1);
        label3.setText(date2);
        label4.setText(vehi);
        label5.setText("Rs "+hourlyrent+" /Hourly");
        grandtotal = hoursno * hourlyrent;
        System.out.println(""+hoursno);
        label1.setText("Rs "+grandtotal);
        yesbtn.setVisible(true);
        yesbtn.setEnabled(false);
        nobtn.setVisible(true);
        nobtn.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from screen1;";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/rentals?autoReconnect=true&useSSL=false","root","1234");
            Statement stmt = con.createStatement();
            String q = "delete from screen2;";
            int rs = stmt.executeUpdate(q);
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error In Connectivity");
        }
        System.exit(0);
    }//GEN-LAST:event_nobtnActionPerformed

    private void yesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesbtnActionPerformed
        // TODO add your handling code here:
        yesbtn.setVisible(false);
        nobtn.setVisible(false);
        termscb.setEnabled(false);
    }//GEN-LAST:event_yesbtnActionPerformed

    private void termscbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termscbActionPerformed
        // TODO add your handling code here:
        if (termscb.isSelected()==true) {
            yesbtn.setEnabled(true);
            nobtn.setEnabled(true);
        }
        else{
            yesbtn.setEnabled(false);
            nobtn.setEnabled(true);
        }
    }//GEN-LAST:event_termscbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JButton nobtn;
    private javax.swing.JCheckBox termscb;
    private javax.swing.JButton yesbtn;
    // End of variables declaration//GEN-END:variables
}
